### ISSUE TITLE
Primeira Reunião

### ISSUE THREAD

**Issue by amadeu01** [training-center/swift-study-group#1]
E aí pessoal, criei a issue para definirmos como começaremos os estudos, tópico esta aberto para sugestões de trilhas, conteúdo, vídeos.. qualquer coisa.

Coloquei aqui para movimentar alguém que não tá no slack mas que viu o git em algum lugar 😄

**Comment by fluiz** [comment]
Opa, tudo bem @amadeu01 ? Andei pensando em seguir o iOS Developer Roadmap https://medium.com/ios-os-x-development/ios-developer-roadmap-c9a24f413457 mas acho que aqui temos nosso espaço para definir um roadmap mais focado nas necessidades locais.

**Comment by amadeu01** [comment]
@fluiz desculpa a demora para te responder.

Então, acho que a primeirsa missão por enquanto é fazer o pessoal chegar até aqui. Eu já fui em um meetup, então sei que o pessoal se empolga em estudar/compartilhar conhecimento. Mas, não sei o motivo que não consigo atrair pessoal para cá. Para o grupo.
Então acho que a gente pode fazer:

1. Atrair mais gente.
2. Definir como iremos seguir com os estudos.

Não sei muito o que o pessoal espera de um grupo de estudos, ou o que o pessoal precisa para deixar o grupo mais atrativo.

**Comment by amadeu01** [comment]
@fluiz você ainda tá no slack do training center?

**Comment by Diego-Brocanelli** [comment]
Olá, pessoal.

Podemos encerrar essa issue, ou ainda se mantém relevante para permanecer aberta?

**Comment by amadeu01** [comment]
Pode fechar!
